# fly.toml app configuration file generated for easyfinder-frontend on 2026-01-06T03:42:00-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'easyfinder-frontend'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
