import { Listing, User } from "./types.js";

/**
 * Demo users
 */
export const demoUsers: User[] = [
  {
    id: "demo-user",
    email: "demo@easyfinder.ai",
    name: "Demo User",
    role: "demo",
    billing: {
      plan: "free",
      status: "canceled",
      current_period_end: new Date(0).toISOString(),
    },
  },
  {
    id: "buyer-user",
    email: "buyer@easyfinder.ai",
    name: "Buyer User",
    role: "buyer",
    billing: {
      plan: "free",
      status: "canceled",
      current_period_end: new Date(0).toISOString(),
    },
  },
  {
    id: "seller-user",
    email: "seller@easyfinder.ai",
    name: "Seller User",
    role: "seller",
    billing: {
      plan: "free",
      status: "canceled",
      current_period_end: new Date(0).toISOString(),
    },
  },
  {
    id: "admin-user",
    email: "admin@easyfinder.ai",
    name: "Admin User",
    role: "admin",
    billing: {
      plan: "free",
      status: "canceled",
      current_period_end: new Date(0).toISOString(),
    },
  },
];

const demoImageLibrary: Record<string, string[]> = {
  excavator: [
    "/demo-images/excavator/1.jpg",
    "/demo-images/excavator/2.jpg",
    "/demo-images/excavator/3.jpg",
    "/demo-images/excavator/4.jpg",
    "/demo-images/excavator/5.jpg",
  ],
  dozer: [
    "/demo-images/dozer/1.jpg",
    "/demo-images/dozer/2.jpg",
    "/demo-images/dozer/3.jpg",
    "/demo-images/dozer/4.jpg",
    "/demo-images/dozer/5.jpg",
  ],
  "skid-steer": [
    "/demo-images/skid-steer/1.jpg",
    "/demo-images/skid-steer/2.jpg",
    "/demo-images/skid-steer/3.jpg",
    "/demo-images/skid-steer/4.jpg",
    "/demo-images/skid-steer/5.jpg",
  ],
  "wheel-loader": [
    "/demo-images/wheel-loader/1.jpg",
    "/demo-images/wheel-loader/2.jpg",
    "/demo-images/wheel-loader/3.jpg",
    "/demo-images/wheel-loader/4.jpg",
    "/demo-images/wheel-loader/5.jpg",
  ],
  backhoe: [
    "/demo-images/backhoe/1.jpg",
    "/demo-images/backhoe/2.jpg",
    "/demo-images/backhoe/3.jpg",
    "/demo-images/backhoe/4.jpg",
    "/demo-images/backhoe/5.jpg",
  ],
  telehandler: [
    "/demo-images/telehandler/1.jpg",
    "/demo-images/telehandler/2.jpg",
    "/demo-images/telehandler/3.jpg",
    "/demo-images/telehandler/4.jpg",
    "/demo-images/telehandler/5.jpg",
  ],
  other: [
    "/demo-images/other/1.jpg",
    "/demo-images/other/2.jpg",
    "/demo-images/other/3.jpg",
    "/demo-images/other/4.jpg",
    "/demo-images/other/5.jpg",
  ],
};

const getCategoryImages = (category: string) =>
  demoImageLibrary[category] ?? demoImageLibrary.other;

const demoListingsBase: Omit<Listing, "images" | "imageUrl">[] = [
  {
    id: "demo-1",
    title: "2020 CAT 320 Excavator",
    description: "Well-maintained excavator with low hours and clean service logs.",
    state: "CA",
    price: 178000,
    hours: 1800,
    operable: true,
    category: "excavator",
    source: "auctionplanet",
    createdAt: "2025-12-10T15:12:00.000Z",
  },
  {
    id: "demo-2",
    title: "2018 Komatsu PC210 Excavator",
    description: "Job-ready excavator with fresh undercarriage inspection.",
    state: "TX",
    price: 154000,
    hours: 3200,
    operable: true,
    category: "excavator",
    source: "ironplanet",
    createdAt: "2025-12-08T10:35:00.000Z",
  },
  {
    id: "demo-3",
    title: "2016 Deere 210G Excavator",
    description: "Balanced excavator with mid-range hours and strong hydraulics.",
    state: "NV",
    price: 122000,
    hours: 4100,
    operable: true,
    category: "excavator",
    source: "machinerytrader",
    createdAt: "2025-12-05T09:20:00.000Z",
  },
  {
    id: "demo-4",
    title: "2021 Volvo EC250 Excavator",
    description: "Late-model excavator, warranty transfer available.",
    state: "AZ",
    price: 206000,
    hours: 950,
    operable: true,
    category: "excavator",
    source: "auctiontime",
    createdAt: "2025-12-12T11:00:00.000Z",
  },
  {
    id: "demo-5",
    title: "2017 CAT D6T Dozer",
    description: "Strong push power with updated blade hydraulics.",
    state: "IA",
    price: 198000,
    hours: 3600,
    operable: true,
    category: "dozer",
    source: "ritchiebros",
    createdAt: "2025-12-03T14:40:00.000Z",
  },
  {
    id: "demo-6",
    title: "2015 Komatsu D65 Dozer",
    description: "Reliable dozer with premium undercarriage.",
    state: "CO",
    price: 148000,
    hours: 5200,
    operable: true,
    category: "dozer",
    source: "ironplanet",
    createdAt: "2025-11-28T12:15:00.000Z",
  },
  {
    id: "demo-7",
    title: "2019 Deere 650K Dozer",
    description: "Low-hour dozer with GPS-ready blade controls.",
    state: "TX",
    price: 214000,
    hours: 1400,
    operable: true,
    category: "dozer",
    source: "auctionplanet",
    createdAt: "2025-12-09T09:05:00.000Z",
  },
  {
    id: "demo-8",
    title: "2014 CAT D5K Dozer",
    description: "Compact dozer, strong for tight sites.",
    state: "WA",
    price: 98000,
    hours: 6400,
    operable: true,
    category: "dozer",
    source: "govplanet",
    createdAt: "2025-11-20T16:55:00.000Z",
  },
  {
    id: "demo-9",
    title: "2020 CAT 262D Skid Steer",
    description: "Compact skid steer with new tires and cab.",
    state: "AZ",
    price: 72000,
    hours: 1100,
    operable: true,
    category: "skid-steer",
    source: "auctiontime",
    createdAt: "2025-12-11T08:30:00.000Z",
  },
  {
    id: "demo-10",
    title: "2018 Bobcat S650 Skid Steer",
    description: "High-flow skid steer with attachment package.",
    state: "CA",
    price: 68000,
    hours: 1900,
    operable: true,
    category: "skid-steer",
    source: "heavyequipment",
    createdAt: "2025-12-01T10:10:00.000Z",
  },
  {
    id: "demo-11",
    title: "2016 Deere 318G Skid Steer",
    description: "Well-kept skid steer with enclosed cab.",
    state: "OR",
    price: 52000,
    hours: 2900,
    operable: true,
    category: "skid-steer",
    source: "machinerytrader",
    createdAt: "2025-11-25T15:20:00.000Z",
  },
  {
    id: "demo-12",
    title: "2021 Takeuchi TL12 Skid Steer",
    description: "Track skid steer, low hours, clean emissions.",
    state: "TX",
    price: 89000,
    hours: 800,
    operable: true,
    category: "skid-steer",
    source: "auctionplanet",
    createdAt: "2025-12-13T13:25:00.000Z",
  },
  {
    id: "demo-13",
    title: "2019 CAT 930M Wheel Loader",
    description: "Production-ready loader with scale system.",
    state: "NV",
    price: 162000,
    hours: 2800,
    operable: true,
    category: "wheel-loader",
    source: "ironplanet",
    createdAt: "2025-12-07T12:45:00.000Z",
  },
  {
    id: "demo-14",
    title: "2017 Volvo L90 Wheel Loader",
    description: "Efficient loader with updated bucket pins.",
    state: "CA",
    price: 148000,
    hours: 4200,
    operable: true,
    category: "wheel-loader",
    source: "ritchiebros",
    createdAt: "2025-12-02T09:00:00.000Z",
  },
  {
    id: "demo-15",
    title: "2015 Deere 544K Wheel Loader",
    description: "Durable loader with strong tire condition.",
    state: "UT",
    price: 118000,
    hours: 6100,
    operable: true,
    category: "wheel-loader",
    source: "auctiontime",
    createdAt: "2025-11-22T11:35:00.000Z",
  },
  {
    id: "demo-16",
    title: "2022 Komatsu WA270 Wheel Loader",
    description: "Late-model loader with low hours and warranty.",
    state: "AZ",
    price: 224000,
    hours: 600,
    operable: true,
    category: "wheel-loader",
    source: "machinerytrader",
    createdAt: "2025-12-14T10:50:00.000Z",
  },
  {
    id: "demo-17",
    title: "2018 CAT 420F Backhoe",
    description: "Backhoe with extendahoe and clean hydraulics.",
    state: "TX",
    price: 98000,
    hours: 2300,
    operable: true,
    category: "backhoe",
    source: "govplanet",
    createdAt: "2025-12-04T08:20:00.000Z",
  },
  {
    id: "demo-18",
    title: "2016 Deere 310SL Backhoe",
    description: "Fleet-maintained backhoe with strong engine hours.",
    state: "CO",
    price: 86000,
    hours: 3600,
    operable: true,
    category: "backhoe",
    source: "auctionplanet",
    createdAt: "2025-11-27T13:05:00.000Z",
  },
  {
    id: "demo-19",
    title: "2019 Case 580N Backhoe",
    description: "Smooth-running backhoe with auxiliary hydraulics.",
    state: "IA",
    price: 104000,
    hours: 1900,
    operable: true,
    category: "backhoe",
    source: "heavyequipment",
    createdAt: "2025-12-06T15:45:00.000Z",
  },
  {
    id: "demo-20",
    title: "2015 CAT 416F Backhoe",
    description: "Budget-friendly backhoe with recent service.",
    state: "NV",
    price: 78000,
    hours: 5200,
    operable: true,
    category: "backhoe",
    source: "auctiontime",
    createdAt: "2025-11-18T09:40:00.000Z",
  },
  {
    id: "demo-21",
    title: "2020 JLG 1055 Telehandler",
    description: "High-reach telehandler with low hours.",
    state: "CA",
    price: 132000,
    hours: 1500,
    operable: true,
    category: "telehandler",
    source: "ritchiebros",
    createdAt: "2025-12-12T16:10:00.000Z",
  },
  {
    id: "demo-22",
    title: "2017 Genie GTH-1056 Telehandler",
    description: "Telehandler with stabilized outriggers.",
    state: "TX",
    price: 118000,
    hours: 2800,
    operable: true,
    category: "telehandler",
    source: "auctionplanet",
    createdAt: "2025-12-01T07:55:00.000Z",
  },
  {
    id: "demo-23",
    title: "2016 CAT TL1055 Telehandler",
    description: "Reliable telehandler with steady boom control.",
    state: "OR",
    price: 98000,
    hours: 4100,
    operable: true,
    category: "telehandler",
    source: "ironplanet",
    createdAt: "2025-11-23T10:30:00.000Z",
  },
  {
    id: "demo-24",
    title: "2022 SkyTrak 8042 Telehandler",
    description: "Late-model telehandler with service contract.",
    state: "AZ",
    price: 148000,
    hours: 900,
    operable: true,
    category: "telehandler",
    source: "machinerytrader",
    createdAt: "2025-12-15T14:15:00.000Z",
  },
];

const inferYearFromTitle = (title: string) => {
  const match = title.match(/\b(19|20)\d{2}\b/);
  return match ? Number(match[0]) : undefined;
};

const inferConditionFromHours = (hours: number) => {
  if (!Number.isFinite(hours)) return undefined;
  if (hours <= 1000) return 4.7;
  if (hours <= 2000) return 4.3;
  if (hours <= 4000) return 3.8;
  if (hours <= 6000) return 3.3;
  if (hours <= 8000) return 2.8;
  return 2.3;
};

export const demoListings: Listing[] = demoListingsBase.map((listing) => {
  const images = getCategoryImages(listing.category);
  const inferredYear = listing.year ?? inferYearFromTitle(listing.title);
  const inferredCondition =
    listing.condition ?? inferConditionFromHours(listing.hours);
  return {
    ...listing,
    year: inferredYear,
    condition: inferredCondition,
    images,
    imageUrl: images[0],
  };
});
